import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

// Add to your stylesheet or as inline style
// eslint-disable-next-line @typescript-eslint/no-unused-vars
const accessibilityStyles = `
  .accessibility-container {
    min-height: fit-content !important;
    height: auto !important;
  }
  
  .accessibility-text {
    word-wrap: break-word;
    overflow-wrap: break-word;
    hyphens: auto;
  }
`;

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}


